import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectorRef, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

type Item = { productId: string; quantity: string; averageCost: string; product: { name: string; baseUnit: string; minStock: string } };
type Move = { id: string; occurredAt: string; type: string; quantity: string; quantityAfter: string; notes?: string; referenceType: string };
type TransformationLine = { productId: string; name: string; baseUnit: string; quantity: number; totalCost: number };
type Transformation = { id: string; code: string; createdAt: string; outputQuantity: string; totalCost: string; notes?: string; outputProduct: { name: string; baseUnit: string }; items: { product: { name: string; baseUnit: string }; quantity: string; totalCost: string }[] };

@Component({
  selector: 'ac-inventory-panel', standalone: true, imports: [CommonModule, FormsModule],
  template: `<section class="workspace"><h2>Inventario</h2>
    <form (ngSubmit)="create()"><input name="name" [(ngModel)]="name" placeholder="Nuevo producto"><select name="unit" [(ngModel)]="unit"><option value="ML">mL</option><option value="G">g</option><option value="UND">Unidad</option></select><input name="min" [(ngModel)]="minStock" type="number" min="0" placeholder="Existencia mínima"><button>Crear producto</button></form>

    <h3>Preparar o combinar productos</h3>
    <p class="status">Crea primero el producto resultante. La preparación rebaja los insumos y le asigna el costo total de estos.</p>
    <form (ngSubmit)="addTransformationLine()"><select name="outputProduct" [(ngModel)]="outputProductId"><option value="" disabled>Producto obtenido</option>@for(i of inventory;track i.productId){<option [value]="i.productId">{{i.product.name}} ({{i.product.baseUnit}})</option>}</select><select name="inputProduct" [(ngModel)]="inputProductId"><option value="" disabled>Producto origen</option>@for(i of compatibleInputs;track i.productId){<option [value]="i.productId">{{i.product.name}} · disponible {{i.quantity}} {{i.product.baseUnit}}</option>}</select><input name="inputQuantity" [(ngModel)]="inputQuantity" type="number" min="0.0001" step="0.0001" placeholder="Cantidad a usar"><button>Agregar insumo</button></form>
    @if(transformationLines.length){<table><thead><tr><th>Producto origen</th><th>Cantidad</th><th>Costo usado</th><th></th></tr></thead><tbody>@for(line of transformationLines;track line.productId){<tr><td>{{line.name}}</td><td>{{line.quantity}} {{line.baseUnit}}</td><td>₡{{line.totalCost}}</td><td><button type="button" (click)="removeTransformationLine(line.productId)">Quitar</button></td></tr>}</tbody></table>}
    <form (ngSubmit)="saveTransformation()"><input name="outputQuantity" [(ngModel)]="outputQuantity" type="number" min="0.0001" step="0.0001" placeholder="Cantidad obtenida"><input name="transformationNotes" [(ngModel)]="transformationNotes" placeholder="Observación de preparación"><span><strong>Costo de insumos: ₡{{transformationCost}}</strong></span><button [disabled]="transformationLines.length < 2">Guardar preparación</button></form>

    <h3>Levantamiento y ajustes</h3><form (ngSubmit)="adjust()"><select name="product" [(ngModel)]="adjustProduct"><option value="" disabled>Producto</option>@for(i of inventory;track i.productId){<option [value]="i.productId">{{i.product.name}}</option>}</select><select name="type" [(ngModel)]="adjustType"><option value="INITIAL">Inventario inicial</option><option value="ADJUSTMENT_IN">Entrada de ajuste</option><option value="ADJUSTMENT_OUT">Salida de ajuste</option></select><input name="quantity" [(ngModel)]="adjustQuantity" type="number" min="0.0001" placeholder="Cantidad">@if(adjustType==='INITIAL'){<input name="cost" [(ngModel)]="unitCost" type="number" min="0.000001" placeholder="Costo unitario obligatorio">}<input name="reason" [(ngModel)]="adjustReason" placeholder="Motivo"><button>{{adjustType==='INITIAL'?'Guardar inventario inicial':'Ajustar inventario'}}</button></form>
    <table><thead><tr><th>Producto</th><th>Existencia</th><th>Mínimo</th><th>Costo promedio</th><th></th></tr></thead><tbody>@for(i of inventory;track i.productId){<tr [class.low]="isLow(i)"><td>{{i.product.name}}</td><td>{{i.quantity}} {{i.product.baseUnit}}</td><td>{{i.product.minStock||'—'}}</td><td>₡{{i.averageCost}}</td><td><button type="button" (click)="setMinimum(i)">Definir mínimo</button><button type="button" (click)="kardex(i)">Kardex</button></td></tr>}</tbody></table>

    <h3>Preparaciones registradas</h3><table><thead><tr><th>Código</th><th>Fecha</th><th>Producto obtenido</th><th>Cantidad</th><th>Costo</th><th></th></tr></thead><tbody>@for(transformation of transformations;track transformation.id){<tr><td>{{transformation.code}}</td><td>{{transformation.createdAt|slice:0:10}}</td><td>{{transformation.outputProduct.name}}</td><td>{{transformation.outputQuantity}} {{transformation.outputProduct.baseUnit}}</td><td>₡{{transformation.totalCost}}</td><td><button type="button" (click)="transformationDetail=transformation">Detalle</button><button type="button" (click)="voidTransformation(transformation)">Anular</button></td></tr>}</tbody></table>
    @if(detail){<div class="detail"><h3>Kardex · {{detail.product.name}}</h3>@for(m of movements;track m.id){<p>{{m.occurredAt|slice:0:10}} · {{m.referenceType}} · {{m.quantity}} · saldo {{m.quantityAfter}} · {{m.notes}}</p>}<button (click)="detail=undefined">Cerrar</button></div>}
    @if(transformationDetail){<div class="detail"><h3>{{transformationDetail.code}} · {{transformationDetail.outputProduct.name}}</h3><p><strong>Producto obtenido:</strong> {{transformationDetail.outputQuantity}} {{transformationDetail.outputProduct.baseUnit}} · ₡{{transformationDetail.totalCost}}</p>@for(item of transformationDetail.items;track item.product.name){<p>{{item.product.name}}: {{item.quantity}} {{item.product.baseUnit}} · ₡{{item.totalCost}}</p>}@if(transformationDetail.notes){<p><strong>Observación:</strong> {{transformationDetail.notes}}</p>}<button type="button" (click)="transformationDetail=undefined">Cerrar</button></div>}
  </section>`
})
export class InventoryPanelComponent {
  inventory: Item[] = []; name = ''; unit = 'ML'; minStock: number | null = null;
  adjustProduct = ''; adjustType = 'INITIAL'; adjustQuantity: number | null = null; unitCost: number | null = null; adjustReason = 'Levantamiento inicial'; detail?: Item; movements: Move[] = [];
  outputProductId = ''; inputProductId = ''; inputQuantity: number | null = null; outputQuantity: number | null = null; transformationNotes = ''; transformationLines: TransformationLine[] = []; transformations: Transformation[] = []; transformationDetail?: Transformation;
  constructor(private http: HttpClient, private cdr: ChangeDetectorRef) { this.load(); }
  load() { this.http.get<Item[]>('http://localhost:3000/api/v1/inventory').subscribe(x => { this.inventory = x; this.cdr.detectChanges(); }); this.loadTransformations(); }
  loadTransformations() { this.http.get<Transformation[]>('http://localhost:3000/api/v1/inventory/transformations').subscribe(x => { this.transformations = x; this.cdr.detectChanges(); }); }
  create() { if (!this.name) return; this.http.post('http://localhost:3000/api/v1/products', { name: this.name, baseUnit: this.unit, minStock: this.minStock ?? 0 }).subscribe({ next: () => { this.name = ''; this.minStock = null; this.load(); }, error: error => window.alert(error.error?.message ?? 'No fue posible crear el producto.') }); }
  get outputProduct() { return this.inventory.find(item => item.productId === this.outputProductId); }
  get compatibleInputs() { return this.inventory.filter(item => item.productId !== this.outputProductId && (!this.outputProduct || item.product.baseUnit === this.outputProduct.product.baseUnit)); }
  get transformationCost() { return this.transformationLines.reduce((sum, line) => sum + line.totalCost, 0); }
  addTransformationLine() { const input = this.inventory.find(item => item.productId === this.inputProductId); if (!this.outputProduct || !input || !this.inputQuantity || this.inputQuantity <= 0) { window.alert('Seleccione el producto obtenido, el insumo y la cantidad a utilizar.'); return; } if (Number(input.quantity) < this.inputQuantity) { window.alert('La cantidad indicada supera el inventario disponible.'); return; } if (input.product.baseUnit !== this.outputProduct.product.baseUnit) { window.alert('Los insumos y el producto obtenido deben usar la misma unidad.'); return; } if (this.transformationLines.some(line => line.productId === input.productId)) { window.alert('Este insumo ya fue agregado.'); return; } this.transformationLines = [...this.transformationLines, { productId: input.productId, name: input.product.name, baseUnit: input.product.baseUnit, quantity: this.inputQuantity, totalCost: this.inputQuantity * Number(input.averageCost) }]; this.inputProductId = ''; this.inputQuantity = null; }
  removeTransformationLine(productId: string) { this.transformationLines = this.transformationLines.filter(line => line.productId !== productId); }
  saveTransformation() { if (!this.outputProduct || !this.outputQuantity || this.transformationLines.length < 2) { window.alert('Indique el producto obtenido, la cantidad obtenida y al menos dos insumos.'); return; } this.http.post('http://localhost:3000/api/v1/inventory/transformations', { outputProductId: this.outputProductId, outputQuantity: this.outputQuantity, notes: this.transformationNotes, items: this.transformationLines.map(line => ({ productId: line.productId, quantity: line.quantity })) }).subscribe({ next: () => { this.transformationLines = []; this.inputProductId = ''; this.outputQuantity = null; this.transformationNotes = ''; this.load(); }, error: error => window.alert(error.error?.message ?? 'No fue posible guardar la preparación.') }); }
  voidTransformation(transformation: Transformation) { const reason = window.prompt(`Motivo para anular ${transformation.code}:`); if (!reason || reason.trim().length < 3) return; this.http.patch(`http://localhost:3000/api/v1/inventory/transformations/${transformation.id}/void`, { reason }).subscribe({ next: () => this.load(), error: error => window.alert(error.error?.message ?? 'No fue posible anular la preparación.') }); }
  adjust() { const initial = this.adjustType === 'INITIAL'; if (!this.adjustProduct || !this.adjustQuantity || this.adjustReason.trim().length < 3 || (initial && !this.unitCost)) { window.alert(initial ? 'Indique producto, cantidad, costo unitario y motivo.' : 'Indique producto, cantidad y motivo.'); return; } this.http.post('http://localhost:3000/api/v1/inventory/adjustments', { productId: this.adjustProduct, type: initial ? 'ADJUSTMENT_IN' : this.adjustType, quantity: this.adjustQuantity, unitCost: initial ? this.unitCost : undefined, isInitial: initial, reason: this.adjustReason }).subscribe({ next: () => { this.adjustQuantity = null; this.unitCost = null; this.adjustReason = initial ? 'Levantamiento inicial' : ''; this.load(); }, error: error => window.alert(error.error?.message ?? 'No fue posible ajustar el inventario.') }); }
  isLow(i: Item) { return Number(i.product.minStock) > 0 && Number(i.quantity) <= Number(i.product.minStock); }
  setMinimum(i: Item) { const value = window.prompt(`Existencia mínima para ${i.product.name}:`, i.product.minStock); if (value === null) return; const minStock = Number(value); if (!Number.isFinite(minStock) || minStock < 0) return; this.http.patch(`http://localhost:3000/api/v1/products/${i.productId}`, { name: i.product.name, baseUnit: i.product.baseUnit, minStock }).subscribe(() => this.load()); }
  kardex(i: Item) { this.detail = i; this.http.get<Move[]>(`http://localhost:3000/api/v1/inventory/movements?productId=${i.productId}`).subscribe(x => { this.movements = x; this.cdr.detectChanges(); }); }
}
