import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectorRef, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

type Item = { productId: string; quantity: string; averageCost: string; product: { code: string; name: string; baseUnit: string; minStock: string } };
type Move = { id: string; occurredAt: string; type: string; quantity: string; quantityAfter: string; notes?: string };

@Component({
  selector: 'ac-inventory-panel', standalone: true, imports: [CommonModule, FormsModule],
  template: `<section class="workspace"><h2>Inventario</h2><form (ngSubmit)="create()"><input name="name" [(ngModel)]="name" placeholder="Nuevo producto"><select name="unit" [(ngModel)]="unit"><option value="ML">mL</option><option value="G">g</option><option value="UND">Unidad</option></select><input name="minStock" [(ngModel)]="minStock" type="number" min="0" placeholder="Existencia mínima"><button>Crear producto</button></form><form (ngSubmit)="adjust()"><select name="adjustProduct" [(ngModel)]="adjustProduct"><option value="" disabled>Producto para ajuste</option>@for(i of inventory;track i.productId){<option [value]="i.productId">{{i.product.name}}</option>}</select><select name="type" [(ngModel)]="adjustType"><option value="ADJUSTMENT_IN">Entrada</option><option value="ADJUSTMENT_OUT">Salida</option></select><input name="quantity" [(ngModel)]="adjustQuantity" type="number" min="0.0001" placeholder="Cantidad"><input name="reason" [(ngModel)]="adjustReason" placeholder="Motivo"><button>Ajustar inventario</button></form><table><thead><tr><th>Producto</th><th>Existencia</th><th>Mínimo</th><th>Costo</th><th></th></tr></thead><tbody>@for(i of inventory;track i.productId){<tr [class.low]="isLow(i)"><td>{{i.product.name}}</td><td>{{i.quantity}} {{i.product.baseUnit}}</td><td>{{i.product.minStock || '—'}}</td><td>₡{{i.averageCost}}</td><td><button type="button" (click)="setMinimum(i)">Definir mínimo</button><button type="button" (click)="kardex(i)">Kardex</button></td></tr>}</tbody></table>@if(detail){<div class="detail"><h3>Kardex · {{detail.product.name}}</h3>@for(m of movements;track m.id){<p>{{m.occurredAt|slice:0:10}} · {{m.type}} · {{m.quantity}} · saldo {{m.quantityAfter}} · {{m.notes}}</p>}<button (click)="detail=undefined">Cerrar</button></div>}</section>`,
  styles: `.workspace{margin-top:28px;padding:24px;border-radius:18px;background:#fff;box-shadow:0 8px 24px rgb(18 63 34 / 10%)}form{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;margin-bottom:12px}input,select{padding:10px;border:1px solid #bed1c1;border-radius:8px}table{width:100%;margin-top:18px;border-collapse:collapse}th,td{padding:10px;text-align:left;border-bottom:1px solid #e3ece4}.low{background:#fff3df}.low td:first-child{font-weight:700;color:#754400}@media(max-width:800px){form{grid-template-columns:1fr}table{font-size:.8rem}}`
})
export class InventoryPanelComponent {
  inventory: Item[] = []; name = ''; unit = 'ML'; minStock: number | null = null; adjustProduct = ''; adjustType = 'ADJUSTMENT_IN'; adjustQuantity: number | null = null; adjustReason = ''; detail?: Item; movements: Move[] = [];
  constructor(private readonly http: HttpClient, private readonly cdr: ChangeDetectorRef) { this.load(); }
  load() { this.http.get<Item[]>('http://localhost:3000/api/v1/inventory').subscribe(items => { this.inventory = items; this.cdr.detectChanges(); }); }
  create() { if (!this.name) { window.alert('Indique el nombre del producto.'); return; } this.http.post('http://localhost:3000/api/v1/products', { name: this.name, baseUnit: this.unit, minStock: this.minStock ?? 0 }).subscribe(() => { this.name = ''; this.minStock = null; this.load(); }); }
  adjust() { if (!this.adjustProduct || !this.adjustQuantity || this.adjustReason.trim().length < 3) { window.alert('Seleccione un producto, indique una cantidad y escriba un motivo de al menos 3 caracteres.'); return; } this.http.post('http://localhost:3000/api/v1/inventory/adjustments', { productId: this.adjustProduct, type: this.adjustType, quantity: this.adjustQuantity, reason: this.adjustReason }).subscribe(() => { this.adjustQuantity = null; this.adjustReason = ''; this.load(); }); }
  isLow(item: Item) { return Number(item.product.minStock) > 0 && Number(item.quantity) <= Number(item.product.minStock); }
  setMinimum(item: Item) { const value = window.prompt(`Existencia mínima para ${item.product.name}:`, item.product.minStock); if (value === null) return; const minStock = Number(value); if (!Number.isFinite(minStock) || minStock < 0) { window.alert('El mínimo debe ser un número igual o mayor que cero.'); return; } this.http.patch(`http://localhost:3000/api/v1/products/${item.productId}`, { name: item.product.name, baseUnit: item.product.baseUnit, minStock }).subscribe(() => this.load()); }
  kardex(item: Item) { this.detail = item; this.http.get<Move[]>(`http://localhost:3000/api/v1/inventory/movements?productId=${item.productId}`).subscribe(movements => { this.movements = movements; this.cdr.detectChanges(); }); }
}
