import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectorRef, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

type Target = { cropId: string; label: string };
type Report = { crop: { name: string; lot: { name: string; farm: { name: string } } }; productionBoxes: number; harvestValue: string; salesRevenue: string; realizedRevenue: string; incomeSource: string; applicationCost: string; expenseCost: string; transportCost: string; totalCost: string; estimatedProfit: string; realizedProfit: string; estimatedProfitabilityPercent: string; realizedProfitabilityPercent: string };

@Component({ selector: 'ac-reports-panel', standalone: true, imports: [CommonModule, FormsModule], template: `
  <section class="workspace"><h2>Reportes por ciclo de cultivo</h2>
    <form (ngSubmit)="loadReport()"><select name="crop" [(ngModel)]="cropId" required><option value="" disabled>Seleccione finca · lote · cultivo</option>@for (target of targets; track target.cropId) { <option [value]="target.cropId">{{ target.label }}</option> }</select><input name="startDate" [(ngModel)]="startDate" type="date" aria-label="Desde"><input name="endDate" [(ngModel)]="endDate" type="date" aria-label="Hasta"><button [disabled]="!cropId">Consultar reporte</button></form>
    @if (report) { <div class="detail report-modal" role="dialog" aria-modal="true"><div class="report-heading"><span>REPORTE DE CICLO</span><h3>{{ report.crop.lot.farm.name }} · {{ report.crop.lot.name }} · {{ report.crop.name }}</h3></div><div class="report-section"><h4>Producción e ingresos</h4><p><span>Cajas producidas</span><strong>{{ report.productionBoxes }}</strong></p><p><span>Valor de cosecha</span><strong>₡{{ report.harvestValue }}</strong></p><p><span>Ventas registradas</span><strong>₡{{ report.salesRevenue }}</strong></p><p><span>Ingreso realizado</span><strong>₡{{ report.realizedRevenue }}</strong></p><small>{{ report.incomeSource === 'VENTAS_REGISTRADAS' ? 'Calculado con ventas registradas.' : 'Calculado con precios confirmados de cosecha.' }}</small></div><div class="report-section"><h4>Costos del ciclo</h4><p><span>Aplicaciones</span><strong>₡{{ report.applicationCost }}</strong></p><p><span>Gastos</span><strong>₡{{ report.expenseCost }}</strong></p><p><span>Transporte</span><strong>₡{{ report.transportCost }}</strong></p><p class="total"><span>Costo total</span><strong>₡{{ report.totalCost }}</strong></p></div><div class="profit-grid"><div><span>Ganancia estimada</span><strong>₡{{ report.estimatedProfit }}</strong><small>{{ report.estimatedProfitabilityPercent }}% de rentabilidad</small></div><div><span>Ganancia realizada</span><strong>₡{{ report.realizedProfit }}</strong><small>{{ report.realizedProfitabilityPercent }}% de rentabilidad</small></div></div><button type="button" (click)="report=undefined">Cerrar</button></div> }
  </section>`, styles: `.workspace{margin-top:28px;padding:24px;background:#fff;border-radius:18px}.workspace form{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px}.workspace input,.workspace select{padding:10px;border:1px solid #bed1c1;border-radius:8px}.report-heading span,.report-section h4{color:#39704a;font-size:.8rem;font-weight:800}.report-section{margin-top:20px}.report-section p{display:flex;justify-content:space-between;gap:20px}.report-section p strong{white-space:nowrap}.total{font-size:1.05rem;font-weight:700}.profit-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.profit-grid div{padding:13px;border-radius:12px;background:#eef7ef}.profit-grid span,.profit-grid small{display:block;color:#39704a}.profit-grid strong{display:block;margin:5px 0;color:#153b24}@media(max-width:700px){.workspace form,.profit-grid{grid-template-columns:1fr}}` })
export class ReportsPanelComponent { targets: Target[]=[]; cropId=''; startDate=''; endDate=''; report?:Report; constructor(private http:HttpClient,private cdr:ChangeDetectorRef){this.http.get<{name:string;lots:{name:string;crops:{id:string;name:string;plantedAt:string;plantedPlants:number;isActive:boolean}[]}[]}[]>('http://localhost:3000/api/v1/agriculture/farms').subscribe(farms=>{this.targets=farms.flatMap(f=>f.lots.flatMap(l=>l.crops.map(c=>({cropId:c.id,label:`${f.name} · ${l.name} · ${c.name} · Siembra: ${c.plantedAt.slice(0,10)} · ${c.plantedPlants} matas${c.isActive?'':' · Finalizado'}`}))));this.cdr.detectChanges()})} loadReport(){if(!this.cropId)return;const params=new URLSearchParams({cropId:this.cropId});if(this.startDate)params.set('startDate',this.startDate);if(this.endDate)params.set('endDate',this.endDate);this.http.get<Report>(`http://localhost:3000/api/v1/finance/crop-profitability?${params}`).subscribe(report=>{this.report=report;this.cdr.detectChanges()})} }
